apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: faizh-com-tls
spec:
  secretName: faizh-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: faizh.com
  dnsNames:
    - faizh.com
    - www.faizh.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - faizh.com
          - www.faizh.com
